### PR TITLE
new: TCPClient class implementing an async tcp client

### PR DESCRIPTION
**Pull request by reinzor**
Related to issue #5 , implementing a TCP client async connection

### CODE REVIEW

**Comment by superjax** [comment]
yeah! please merge!

**Comment by reinzor** [comment]
@dpkoch , is this repo maintained?

**Comment by dpkoch** [comment]
@reinzor Yes, sorry, I got busy and then this PR slipped my mind. This looks really great, thank you for contributing! I'll get this merged in next week

**Comment by dpkoch** [comment]
@reinzor Took me a minute to get up to speed on the TCP client/server stuff, but this is really great. Thanks for being so thorough and including an example and documentation!

**Pull request merged**
